//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uk.JohnCook.dotnet.EditableCMDLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("uk.JohnCook.dotnet.EditableCMDLibrary.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmd.exe.
        /// </summary>
        public static string commandPromptFilename {
            get {
                return ResourceManager.GetString("commandPromptFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///{1}
        ///.
        /// </summary>
        public static string commandPromptHeaderFormat {
            get {
                return ResourceManager.GetString("commandPromptHeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [Version {1}].
        /// </summary>
        public static string commandPromptVerFormat {
            get {
                return ResourceManager.GetString("commandPromptVerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (c) Microsoft Corporation. All Rights Reserved..
        /// </summary>
        public static string commandPromptWindowsOSCopyright {
            get {
                return ResourceManager.GetString("commandPromptWindowsOSCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Windows.
        /// </summary>
        public static string commandPromptWindowsOSName {
            get {
                return ResourceManager.GetString("commandPromptWindowsOSName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Prompt.
        /// </summary>
        public static string commandPromptWindowTitle {
            get {
                return ResourceManager.GetString("commandPromptWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1AAAF7F5-4BFC-40B3-B79B-7AC99E426951}.
        /// </summary>
        public static string debugSessionGuid {
            get {
                return ResourceManager.GetString("debugSessionGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMSPEC.
        /// </summary>
        public static string envKeyCommandSpecifier {
            get {
                return ResourceManager.GetString("envKeyCommandSpecifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Break.
        /// </summary>
        public static string logCtrlBreak {
            get {
                return ResourceManager.GetString("logCtrlBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+C.
        /// </summary>
        public static string logCtrlC {
            get {
                return ResourceManager.GetString("logCtrlC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-ddTHHmmss.ffff.
        /// </summary>
        public static string logDateFormat {
            get {
                return ResourceManager.GetString("logDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z.
        /// </summary>
        public static string logDateTimezoneZulu {
            get {
                return ResourceManager.GetString("logDateTimezoneZulu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string logEnter {
            get {
                return ResourceManager.GetString("logEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [.
        /// </summary>
        public static string logPrecedingCharacter {
            get {
                return ResourceManager.GetString("logPrecedingCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ].
        /// </summary>
        public static string logProceedingCharacter {
            get {
                return ResourceManager.GetString("logProceedingCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System error {0} has occurred.
        ///
        ///.
        /// </summary>
        public static string netCommandErrorFormat {
            get {
                return ResourceManager.GetString("netCommandErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///.
        /// </summary>
        public static string netCommandStatusFormat {
            get {
                return ResourceManager.GetString("netCommandStatusFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Microsoft\Windows NT\CurrentVersion.
        /// </summary>
        public static string win10RegKeyUBR {
            get {
                return ResourceManager.GetString("win10RegKeyUBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UBR.
        /// </summary>
        public static string win10RegNameUBR {
            get {
                return ResourceManager.GetString("win10RegNameUBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string win10VersionDefaultUBR {
            get {
                return ResourceManager.GetString("win10VersionDefaultUBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1}.{2}.{3}.
        /// </summary>
        public static string win10VersionFormat {
            get {
                return ResourceManager.GetString("win10VersionFormat", resourceCulture);
            }
        }
    }
}
